# Generated by Django 2.2.7 on 2020-02-18 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200217_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslettersubscription',
            name='read',
        ),
    ]
