# Generated by Django 2.2.7 on 2020-02-23 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_newslettersubscription_read'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
